### ISSUE TITLE
Labeler is not setting person_country_code and person_region_code

### ISSUE THREAD

**Issue by wangyaopw** [world-federation-of-advertisers/virtual-people-core-serving#51]
The [labeler](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/5043e4658cfddadc47aa46f9fe555b364a2fbda1/src/main/cc/wfa/virtual_people/core/labeler/labeler.cc#L121) is not setting `person_country_code` and `person_region_code` when converting a LabelerInput to LabelerEvent.

These two fields are important if we use the [compiler](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/main/src/main/cc/wfa/virtual_people/training/model_compiler/compiler.cc) to compile a model, since it would add 'person_country_code' and 'person_region_code' filters based on the census attribute. For example, like [this](https://github.com/world-federation-of-advertisers/virtual-people-training/blob/main/src/test/cc/wfa/virtual_people/training/model_compiler/test_data/compiled_node_for_population_node.textproto#L71-L82). If the labeler doesn't add these two fields in the event, the model will match none of the inputs.

**Comment by wliue** [comment]
This is "work as intended".
For person_country_code, person_region_code, and other fields in LabelerEvent in general, the labeler doesn't know how to set these, rather, they are set/updated by the model as the event traverse the tree.

**Comment by wangyaopw** [comment]
Got it. Thanks for the explanation. I am closing it.
